dist: focal
language: python

stages:
  - coding rules
  - test

jobs:
  include:
    - stage: coding rules
      python: 3.8
      script: tox -e flake8 
    - stage: coding rules
      python: 3.8
      script: tox -e black 
    - stage: tests
      python: 3.6
      install:
        - python -m pip install --upgrade pip
        - pip install -r requirements-dev.txt
      script: coverage run -m pytest -v tests
    - stage: tests
      python: 3.7
      install:
        - python -m pip install --upgrade pip
        - pip install -r requirements-dev.txt
      script: coverage run -m pytest -v tests
      after_success:
        - pip install coveralls
        - coveralls
