HTTPDBG_CURRENT_GROUP = "HTTPDBG_CURRENT_GROUP"
HTTPDBG_CURRENT_INITIATOR = "HTTPDBG_CURRENT_INITIATOR"
HTTPDBG_CURRENT_TAG = "HTTPDBG_CURRENT_TAG"
HTTPDBG_SUBPROCESS_DIR = "HTTPDBG_SUBPROCESS_DIR"

HTTPDBG_LOG_LEVEL = "HTTPDBG_LOG_LEVEL"
HTTPDBG_LOG_PATH = "HTTPDBG_LOG_PATH"
